config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

 resources :users, except: [:new]
 resources :instructors, only: [:index]
 resources :lessons, only: [:index, :show, :new, :create, :edit, :update, :destroy]
 resources :sessions, only: [:new, :create, :destroy]

 get '/instructor/:id', to: "instructors#show", as: 'instructor'
 get '/signup', to: "users#new", as: 'signup' 
 get '/login', to: "sessions#new", as: 'login'
 post '/login', to: "sessions#create"
 delete '/logout', to: "sessions#destroy", as: 'logout'
 delete '/remove', to: "users#destroy", as: 'remove'
#  delete 'delete', to: "lessons#destroy", as: 'cancel'

  



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driving_range.rb
class DrivingRange < ApplicationRecord
   belongs_to :location
   belongs_to :user 

   validates :date, presence: true 
   validates :start_time, presence: true 
   validates :end_time, presence: true 
   validates :spot, presence: true 
   validates :location_id, presence: true 
   validates :user_id, presence: true 

end

app/models/instructor.rb
class Instructor < ApplicationRecord
   has_many :lessons
   has_many :users, through: :lessons
   belongs_to :location

   validates :first_name, presence: true 
   validates :last_name, presence: true 
   validates :email, presence: true, uniqueness: true 
   validates :password, presence: true, length: { in: 6..20 }

   has_secure_password

   def full_name
      "#{first_name} #{last_name}"
   end

   # def instructor_location
   #    city = self.lessons.select { |lesson| lesson.city }
   # end

   
end

app/models/lesson.rb
class Lesson < ApplicationRecord
   belongs_to :user
   belongs_to :instructor
   belongs_to :location

   validates :date, presence: true 
   validates_format_of :date, presence: true, :with => /\d{2}\/\d{2}\/\d{4}/, :message => "must be in the following format: mm/dd/yyyy"
   # validates :date, numericality: { greater_than_or_equal_to: Date.today.year }
   validates :time, presence: true 
   # validates :hand_position, :inclusion => { :in => %w(Fiction Non-Fiction) }

   def name
      list = [ "Front 9 - New Golfers", "Back 9 - Beginner Golfers", "Tee Up - Intermediate", "Tee Up - Experienced" ]
   end
   

end

app/models/location.rb
class Location < ApplicationRecord
   has_many :driving_ranges
   has_many :instructors
   has_many :lessons

   def city_state
      "#{city}, #{state}"
   end
   

end

app/models/user.rb
class User < ApplicationRecord
   has_many :lessons
   has_many :instructors, through: :lessons
   has_many :driving_ranges

   validates :first_name, presence: true 
   validates :last_name, presence: true 
   validates :email, presence: true, uniqueness: true 
   validates :phone_number, presence: true, format: { with: /\d{3}-\d{3}-\d{4}/, message: "must be in xxx-xxx-xxxx format" }
   validates :password, presence: true, length: { in: 6..20 }


   has_secure_password 

   def full_name
      "#{first_name} #{last_name}"
   end

   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    @current_user ||= User.find_by(id: session[:id]) if session[:id] 
   end 

  # def current_user
  #   User.find_by(id: session[:id])
  # end 

  def logged_in?
    !!current_user
  end 


  # def not_logged_in
  #   redirect_to login_path unless logged_in?
  # end 

end

app/controllers/driving_ranges_controller.rb
class DrivingRangesController < ApplicationController

   def index
      @driving_ranges = Driving_Range.all
   end

   def show
      @driving_range = Driving_Range.find(params[:id])
   end

   def new
      @driving_range = Driving_Range.new
   end

   def create
      @driving_range = Driving_Range.new(params[:id])
      if @driving_range.save
         redirect_to driving_range_path(@driving_range)
      else
         render :new
      end
   end

   def edit
      @driving_range = Driving_Range.find(params[:id])
   end

   def update
      @driving_range = Driving_Range.find(params[:id])
      if @driving_range.update(driving_range_params)
         redirect_to driving_range_path(@driving_range)
      else
         render :edit 
      end
   end

   def destroy
      Driving_Range.find(params[:id]).destroy
      redirect_to driving_ranges_path
   end

   private

   def driving_range_params
      params.require(:lesson).permit(:date, :start_time, :end_time, :spot, :location_id, :user_id)
   end
   
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController

   def index
      @instructors = Instructor.all
   end

   def show
      @instructor = Instructor.find(params[:id])
   end


end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController


   def index
      @lessons = Lesson.all
   end

   def show
      @lesson = Lesson.find(params[:id])
   end

   def new
      @lesson = Lesson.new
   end

   def create
      @lesson = Lesson.new(lesson_params)
      if @lesson.save 
         redirect_to lesson_path(@lesson)
      else
         render :new 
      end
   end


   def edit
      @lesson = Lesson.find(params[:id])
   end

   def update
      @lesson = Lesson.find(params[:id])
      if @lesson.update(lesson_params)
         redirect_to lesson_path(@lesson)
      else
         render :edit
      end
   end

   def destroy
      Lesson.find(params[:id]).destroy
      redirect_to user_path(session[:id])
   end

   private

   def lesson_params
      params.require(:lesson).permit(:date, :time, :instructor_id, :user_id, :location_id, :skill_level, :hand_position, :lesson_name)
   end
   
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

   def index
      @locations = Location.all
   end

   def show
      @location = Location.find(params[:id])
   end


   private

   def location_params
      params.require(:location).permit(:city, :state, :phone_number)
   end
   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new 
    @user = User.new
    
  end 

  def create
    user = User.find_by(email: params[:user][:email].downcase)
    

     if user && user.authenticate(params[:user][:password])      
      session[:id] = user.id
      flash[:notice]="Logged in successfully"
      redirect_to user
     else
      flash[:errors] ='Email or Password is incorrect'
      redirect_to login_path
     end 
  end 

  def destroy
    session.clear
    flash[:notice]="Logged out successfully"

    redirect_to root_path


  end 




end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :logged_in?, only: [:show]
  
   
   def show
      
      @user = User.find(session[:id])
   end

   def new
      @user = User.new
   end

   def create
      @user = User.new(user_params)
      if @user.valid?
         @user.save
         redirect_to user_path(@user)
      else
         flash[:errors]=@user.errors.full_messages
         render :new
      end
   end

   def edit
      @user = User.find(params[:id])

   end

   def update
      @user = User.find(params[:id])
     if  @user.update(user_params)
       redirect_to user_path(@user)
     else
      render :edit
     end 
   end

   def destroy
      # @user.destroy
      # session[:user_id] = nil if @user == current_user
      User.find(id: params[:id]).destroy
      redirect_to root_path
   end

   private

   def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone_number, :password)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find_by(id: session[:id]) if session[:id]  end 

  def current_user
    User.find_by(id: session[:id])
  end 

  def logged_in?
    !!current_user
  end 
  

  def not_logged_in
    redirect_to login_path unless logged_in?
  end 

  

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/instructors/index.html.erb
<br><br><br><br><br><br>
<center><h1>Meet Our Instructors</h1></center>
<br><br>
<% @instructors.each do |instructor| %>

  
    <img src="<%= instructor.img_url %>" width =10% align = "left"/><br>

      
<table>
   <tr>
      <td></td>
   </tr>
</table>


<% end %>

app/views/instructors/show.html.erb
<br><br><br><br><br>
<center><h2>Meet Our Pro Instructor, <%= @instructor.full_name %>!</h2></center>

<hr>

<img src="<%= @instructor.img_url %>" width = 300px align = "left"/><br>
<font size="3">
<b>Name:</b> &nbsp; <%= @instructor.full_name %> <br>
<br>
<b>Bio: </b> &nbsp; <%= @instructor.bio %><br>
<br>
<b>Email: </b> &nbsp; <%= @instructor.email %><br>
<br>
<b>GolfLive Location: </b> &nbsp; 
<%= @instructor.location.city_state %>

</font>
<hr>

app/views/layouts/_navbar.html.erb

        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ml-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ml-auto">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#services">Lessons</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#team">Instructors</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">Contact</a></li>
                        <li class="nav-item"><%= link_to 'Home', root_path, class:"nav-link", method: :get %></li>

                        <% if logged_in? %>
                            <li class="nav-item"><%= link_to 'logout', logout_path, class:"nav-link", method: :delete %></li>
  
                        <%else%>
                            <li class="nav-item"><%= link_to 'Log in', login_path, class:"nav-link", method: :get %></li>
                            <li class="nav-item"><%= link_to 'Sign up', signup_path, class:"nav-link", method: :get %></li>
                        </li>
                        <%end%>
                    </ul>
                </div>
            </div>
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GolfLive</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="icon" type="image/x-icon" href="startbootstrap-agency-pages/assets/img/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="startbootstrap-agency-pages/css/styles.css" rel="stylesheet" />
  </head>

  <body id="page-top">
  <%= render 'layouts/navbar'%>

    <%= yield %>
  
  </body>
  <footer>
  <!-- Bootstrap core JS-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Third party plugin JS-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
  <!-- Contact form JS-->
  <script src="startbootstrap-agency-pages/assets/mail/jqBootstrapValidation.js"></script>
  <script src="startbootstrap-agency-pages/assets/mail/contact_me.js"></script>
  <!-- Core theme JS-->
  <script src="startbootstrap-agency-pages/js/scripts.js"></script>
  </footer>
</html>

app/views/lessons/_form.html.erb
<br><br><br><br><br><br>

<center><h2>Lesson Registration Form</h2></center>
<br>
<table align="center">

  <tr>
      <td>
      <br>

<ul>
<% if @lesson.errors.any? %>
  <% @lesson.errors.full_messages.each do |err| %>
    <li style="color:red"> <%=err %></li>
    </ul>
    <%end%>
 <%end %>
<%= form_for @lesson do |f| %>
 
   <%# Date: <%=f.date_select :date %> 
  <%# Date: <%=f.date_field :date %> 
  Name: &nbsp; <%= f.collection_select :user_id, User.all, :id, :full_name, :prompt => 'Enter Full Name' %><br />
   <br/>
  Lesson Name: &nbsp; <%= f.select :lesson_name, [ 'Front 9 - New Golfers','Back 9 - Beginner Golfers','Tee Up - Intermediate', 'Tee Up - Experienced' ], :prompt => 'Select One' %> <br />
  <br/>
  Instructor: &nbsp; <%= f.collection_select :instructor_id, Instructor.all, :id, :full_name, :prompt => 'Select One' %><br />
   <br/>
  Date: &nbsp; <%= f.text_field :date %> <br />
    <%# Date: <%=f.date_field :date %> 
    <%# Ask about how to use date_field / validation %>
  <br/>
  Time: &nbsp; <%= f.time_field :time %> <br />
  <br/>
  Location: &nbsp; <%=f.collection_select :location_id, Location.all, :id, :city_state %> <br />
  <br/>
  Skill Level: &nbsp; <%= f.select :skill_level, [ 'Beginner','Intermediate','Advanced' ], :prompt => 'Select One' %> <br/>
  <br/> 
  Hand Position: &nbsp; <%= f.select :hand_position, [ 'Right','Left' ], :prompt => 'Select One' %> <br/>
  <br/>
   

   <%=f.submit 'Sign-Up' %>
 <%end %>
 
  </td>
   </tr>
 </table>

app/views/lessons/edit.html.erb
<br><br><br><br><br><br>

<center><h2>Lesson Registration Form</h2></center>
<br>
<table align="center">

  <tr>
      <td>
      <br>

<ul>
<% if @lesson.errors.any? %>
  <% @lesson.errors.full_messages.each do |err| %>
    <li style="color:red"> <%=err %></li>
    </ul>
    <%end%>
 <%end %>
<%= form_for @lesson do |f| %>
 
   <%# Date: <%=f.date_select :date %> 
  <%# Date: <%=f.date_field :date %> 
  Name: &nbsp; <%= f.collection_select :user_id, User.all, :id, :full_name, :prompt => 'Enter Full Name' %><br />
   <br/>
  Lesson Name: &nbsp; <%= f.select :lesson_name, [ "Front 9 - New Golfers", "Back 9 - Beginner Golfers", "Tee Up - Intermediate", "Tee Up - Experienced" ], :prompt => 'Select Lesson' %> <br />
  <br/>
  Instructor: &nbsp; <%= f.collection_select :instructor_id, Instructor.all, :id, :full_name, :prompt => 'Select Instructor' %><br />
   <br/>
  Date: &nbsp; <%= f.text_field :date %> <br />
    <%# Date: <%=f.date_field :date %> 
    <%# Ask about how to use date_field / validation %>
  <br/>
  Time: &nbsp; <%= f.select :time, [ '9:00 AM','10:00 AM','11:00 AM', '1:00 PM', '2:00 PM', '3:00 PM', '4:00 PM', '5:00 PM' ], :prompt => 'Select Time' %> <br />
  <br/>
  Location: &nbsp; <%=f.collection_select :location_id, Location.all, :id, :city_state %> <br />
  <br/>
  Skill Level: &nbsp; <%= f.select :skill_level, [ 'Beginner','Intermediate','Advanced' ], :prompt => 'Select Skill Level' %> <br/>
  <br/> 
  Hand Position: &nbsp; <%= f.select :hand_position, [ 'Right','Left' ], :prompt => 'Select One' %> <br/>
  <br/>
   

   <%=f.submit 'Update' %>
 <% end %>
 
  </td>
   </tr>
 </table>

app/views/lessons/index.html.erb
<!DOCTYPE html>
<html >
<head>
  <style>
      .flex-container {
         display: flex;
         align-items: center; /* Use another value to see the result */
         width: 100%;
         height: 420px;
         background-color: #1faadb;
      }
      .flex-container > div {
         padding-right: 25px; 
         padding-left: 25px;
         width: 40%;
         height: 370px;
         margin: 10px;
         border-radius: 4px;
         background-color: #8ebf42;
         font-size: 12px;
      }
      h2 {
         font-size: 35px;
      }
      h3 {
         font-size: 18px;
         font-weight: bold; 
         text-align: center;
      }
    </style>
  </head>
   <body>
      <br><br><br><br>
      <center><h2>GolfLive Lessons</h2></center>
      <br>
    <div class="flex-container">
      <div>
         <p>
         <h3>Front 9:<br> New Golfers</h3><br>
         The <i><b>Front 9</b></i> is designed for the new golfer. 
         Ideal for someone that has never held a golf club before or brand new to golf.
         Students will learn the fundamentals of the full swing, putting and chipping. 
         Basic rules, etiquette, pace of play and golf terminology will also be covered during this lesson.
         <br><br>
         <b>Duration:</b> 1 hour<br>
         <b>Price:</b> $60/lesson<br><br>

         <b><%= link_to 'Click to Book Lesson', new_lesson_path %></b>
         <br>
         </p>
      </div>

      <div>
         <p>
         <h3>Back 9:<br> Beginner Golfers</h3><br>
         The <i><b>Back 9</b></i> is designed for the golfer with a bit of experience; 
         whether from instruction, driving range, or just being around the game.
         Students will learn the fundamentals of the full swing, putting and chipping.
         This class is designed as a follow-up for students who have taken the "Front 9" 
         program or have played golf before. 
      
         <br><br>
         <b>Duration:</b> 1 hour<br>
         <b>Price:</b> $60/lesson<br><br>

          <b><%= link_to 'Click to Book Lesson', new_lesson_path %></b>
         </p>
      </div>
 
       <div>
         <p>
         <h3>Tee-Up:<br> Intermediate</h3><br>
         The <i><b>Tee-Up: Intermediate</b></i> is designed for the golfer who has taken the 
         "Back 9" level or has had some previous technical instruction. This class focuses on 
         what and how to practice properly and teaches the student how to better manager their 
         game on the course when in different situations. 
         
         <br><br>
         <b>Duration:</b> 2 hours<br>
         <b>Price:</b> $80/lesson<br><br>

          <b><%= link_to 'Click to Book Lesson', new_lesson_path %></b>
         </p>
      </div>


      <div>
         <p>
         <h3>Tee-Up: <br>Experienced</h3><br>
         The <i><b>Tee-Up: Experienced</b></i> lesson is geared towards golfers who have had 
         previous technical instruction and designed to establish fundamentals to break 100 
         and consistently score in the 90's. Students will have their golf swing videoed and 
         analyzed, work on their short game and spend time on the course to improve course 
         skills.
         
         <br><br>
         <b>Duration:</b> 2 hours<br>
         <b>Price:</b> $100/lesson<br><br>

          <b><%= link_to 'Click to Book Lesson', new_lesson_path %></b>
         </p>
      </div>

    </div>
  



</body>
</html>

app/views/lessons/new.html.erb

  <div id="page-top">

<br><br><br><br><br><br>

<center><h2>Lesson Registration Form</h2></center>
<br>
<table align="center">

  <tr>
      <td>
      <br>

<ul>
<% if @lesson.errors.any? %>
  <% @lesson.errors.full_messages.each do |err| %>
    <li style="color:red"> <%=err %></li>
    </ul>
    <%end%>
 <%end %>
<%= form_for @lesson do |f| %>
 
   <%# Date: <%=f.date_select :date %> 
  <%# Date: <%=f.date_field :date %> 
  Name: &nbsp; <%= f.collection_select :user_id, User.all, :id, :full_name, :prompt => 'Enter Full Name' %><br />
   <br/>
  Lesson Name: &nbsp; <%= f.select :lesson_name, [ "Front 9 - New Golfers", "Back 9 - Beginner Golfers", "Tee Up - Intermediate", "Tee Up - Experienced" ], :prompt => 'Select Lesson' %> <br />
  <br/>
  Instructor: &nbsp; <%= f.collection_select :instructor_id, Instructor.all, :id, :full_name, :prompt => 'Select Instructor' %><br />
   <br/>
  Date: &nbsp; <%= f.text_field :date %> <br />
    <%# Date: <%=f.date_field :date %> 
    <%# Ask about how to use date_field / validation %>
  <br/>
  Time: &nbsp; <%= f.select :time, [ '9:00 AM','10:00 AM','11:00 AM', '1:00 PM', '2:00 PM', '3:00 PM', '4:00 PM', '5:00 PM' ], :prompt => 'Select Time' %> <br />
  <br/>
  Location: &nbsp; <%=f.collection_select :location_id, Location.all, :id, :city_state %> <br />
  <br/>
  Skill Level: &nbsp; <%= f.select :skill_level, [ 'Beginner','Intermediate','Advanced' ], :prompt => 'Select Skill Level' %> <br/>
  <br/> 
  Hand Position: &nbsp; <%= f.select :hand_position, [ 'Right','Left' ], :prompt => 'Select One' %> <br/>
  <br/>
   

   <%=f.submit 'Sign-Up' %>
 <% end %>
 
  </td>
   </tr>
 </table>

app/views/lessons/show.html.erb
<br><br><br><br><br><br>
<center><h2>Lesson Confirmation</h2></center>
<br><br>

   <center><font size="5px">
   Hi <b><%= @lesson.user.first_name %></b>, your lesson has been confirmed! 
   </font></center>
   <br>
   <table style="width:400px" cellpadding="2px" align="center">
      <tr>
      <th>Date:</th>
      <td><%= @lesson.date %></td>
   </tr>
   <tr>
      <th>Time:</th>
      <td><%= @lesson.time %></td>
   </tr>
   <tr>
      <th style="width:40%">Lesson:</th>
      <td style="width:60%"><%= @lesson.lesson_name %></td>
   </tr>
   <tr>
      <th>Instructor:</th>
      <td><%= @lesson.instructor.full_name %> </td>
   </tr>
   <tr>
      <th>Location:</th>
      <td><%= @lesson.location.city_state %> </td>
   </tr>
   <tr>
      <th>Skill Level:</th>
      <td><%= @lesson.skill_level %></td>
   </tr>
   <tr>
      <th>Hand Position:</th>
      <td><%= @lesson.hand_position %> </td>
   </tr>
   <tr>
      <th> </th>
      <td> </td>
   </tr>
   
</table>
   
    
<table style="width:400px" cellpadding="2px" align="center">

   <tr>
      <td>
        <br> <hr><br>
      <font size="2px">
      <center><b><%= link_to 'Go to My Lesson Page', user_path %></b></center>


      <br>
      <b>Ready to schedule another lesson? &nbsp;
      <%= link_to 'Book New Lesson', new_lesson_path %></b><br>
      <b>Need to make changes to this lesson? &nbsp;
      <%= link_to "Update Lesson", edit_lesson_path %></b> &nbsp;
      <br> <br>
     
      <%= form_for @lesson, method: :delete do |f| %> <%= f.submit "Delete Lesson" %><% end %>
      </font>
      </td>
   </tr>
  
   
</table>

app/views/users/_form.html.erb

  
<div class="container">
<div class="row justify-content-center">
<div class="col-10">

<ul>
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |err| %>
    <li style="color:red"> <%=err %></li>
    </ul>
    <%end%>
 <%end %>

<%= form_for @user, class: "shadow p-3 mb-3 bg-info rounded" do |f| %>
  <div class="form-group row">
    <%= f.label :first_name, class: "col-2 col-form-label text-light" %>
    <div class="col-7">
    <%= f.text_field :first_name, class: "form-control shadow rounded", placeholder: "First name" %>
    </div>
  </div>
  

  <div class="form-group row">
    <%= f.label :last_name, class: "col-2 col-form-label text-light" %>
      <div class="col-7">
    <%= f.text_field :last_name, class: "form-control shadow rounded", placeholder: "Last name" %>
      </div>
   </div>

   <div class="form-group row">
    <%= f.label :email, class: "col-2 col-form-label text-light" %>
      <div class="col-7">
    <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Email" %>
      </div>
   </div>
    

    <div class="form-group row">
    <%= f.label :phone_number, class: "col-2 col-form-label text-light" %>
      <div class="col-7">
    <%= f.telephone_field :phone_number, class: "form-control shadow rounded", placeholder: "Phone Number" %>
      </div>
   </div>
    
   <div class="form-group row">
    <%= f.label :password, class: "col-2 col-form-label text-light" %>
      <div class="col-7">
    <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Password" %>
      </div>
   </div>

    <div class="form-group row justify-content-center">
    <%= f.submit class: "btn btn-outline-dark btn-lg" %>
    </div>
<% end %>
</div>
<div class="mb-1">
 <%= link_to '[ return home ]', root_path, class: "text-info" %> 

</div>
</div>
</div>

app/views/users/edit.html.erb
</br></br></br></br></br></br></br>

<center><h1>Edit profile </h1></center>

<%=render 'form' %>

app/views/users/home.html.erb

  <div class="basic-image basic-large">
        
  <img src="https://www.villagelinksgolf.com/images/slideshows/banner_1.jpg" alt="Topgolf Events" style=" width: 100%; height: 100%">
  
</div>

app/views/users/new.html.erb
</br></br></br></br></br></br></br>

<center><h1>New User Sign-Up Form</h1></center>

<%=render 'form' %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<title>GolfLive!</title>
<style>
.lessonTable {
   width: 1000px;
   border-bottom: 1px solid #ddd;
}

</style>

<br><br><br><br>

</br>
</br>
<div class="container">
<div class="row justify-content-left">
<center><h1>Welcome <%= @user.first_name %>!</h1></center>
<hr>
<table style="width:240px" cellpadding="8px">
   <tr>
      <th style="width:40%">Name:</th>
      <td style="width:60%"><%= @user.full_name %></td>
   </tr>
   <tr>
      <th>Email:</th>
      <td><%= @user.email %></td>
   </tr>
   <tr>
      <th>Phone:</th>
      <td><%= @user.phone_number %></td>
   </tr>
</table>
<h3></h3>
<br />
<hr>

<h3>Upcoming Lessons</h3>
<div align="right"><b><%= link_to 'Book New Lesson', new_lesson_path %></b></div><br>
<h3></h3>
<table class="lessonTable" cellpadding="8px">
   <tr>
     
      <th style="width:15%"> Date </th>
      <th style="width:25%"> Lesson </th>
      <th style="width:10%"> Time </th>
      <th style="width:20%"> Instructor </th>
      <th style="width:15%"> Location </th>
      <th style="width:25%"> Update </th>
     
   </tr>
   <tr>
      <% @user.lessons.each do |lesson| %>
      <td><%= link_to lesson.date, lesson_path(lesson.id) %></td>
      <td><%= lesson.lesson_name %></td>
      <td><%= lesson.time %></td>
      <td><%= lesson.instructor.full_name %></td>
      <td><%= lesson.location.city_state %></td>
      <td><%= link_to "Edit", edit_lesson_path(lesson) %> &nbsp; | &nbsp; <%= link_to "Delete", lesson_path(lesson), method: :delete %></td>

   </tr>
      <% end %>
</table>

<h3></h3>
<br />
<hr>
<div class="col-4">
<%= button_to "Edit", edit_user_path, class: "btn btn-outline-dark form-control shadow rounded", method: :get %>
<%= button_to "Delete", remove_path, class: "btn btn-outline-dark form-control shadow rounded", method: :delete %> 
<%= button_to "Log out", logout_path, class: "btn btn-outline-dark form-control shadow rounded", method: :delete %>
</div>


</div>
</div>